# Generated by Django 4.2.4 on 2023-08-03 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("links", "0003_initial"),
    ]

    operations = [
        migrations.DeleteModel(name="Link",),
    ]
