# Generated by Django 4.2.4 on 2023-08-03 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("links", "0006_alter_link_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="link",
            name="timestamp",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
